AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.7
  Exclude:
    - spec/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  # We have a lot of very long lines in the code to fix,
  # this is a start but we should aim to lower it to
  # at least 120
  Max: 155

Style/FormatStringToken:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
