module Deliveries
  module Couriers
    module Envialia
      module Shipments
        class Create
          module Defaults
            PARAMS = {
              strCodAgeCargo: '',
              strCodAgeOri: '',
              strAlbaran: '',
              dtFecha: '', # DDMMYYYY
              strCodAgeDes: '',
              strCodTipoServ: '',
              strCodCli: '',
              strCodCliDep: '',
              strNomOri: '',
              strTipoViaOri: '',
              strDirOri: '',
              strNumOri: '',
              strPisoOri: '',
              strPobOri: '',
              strCPOri: '',
              strCodProOri: '',
              strTlfOri: '',
              strNomDes: '',
              strTipoViaDes: '',
              strDirDes: '',
              strNumDes: '',
              strPisoDes: '',
              strPobDes: '',
              strCPDes: '',
              strCodProDes: '',
              strTlfDes: '',
              intDoc: '',
              intPaq: '',
              dPesoOri: '',
              dAltoOri: '',
              dAnchoOri: '',
              dLargoOri: '',
              dReembolso: '',
              dValor: '',
              dAnticipo: '',
              dCobCli: '',
              strObs: '',
              boSabado: '',
              boRetorno: '',
              boGestOri: '',
              boGestDes: '',
              boAnulado: '',
              boAcuse: '',
              strRef: '',
              strCodSalRuta: '',
              dBaseImp: '',
              dImpuesto: '',
              boPorteDebCli: '',
              strPersContacto: '',
              strCodPais: '',
              strDesMoviles: '',
              strDesDirEmails: '',
              strFranjaHoraria: '',
              dtHoraEnvIni: '',
              dtHoraEnvFin: '',
              boInsert: '',
              strCampo1: '',
              strCampo2: '',
              strCampo3: '',
              strCampo4: '',
              strCampo5: '',
              boPagoDUAImp: '',
              boPagoImpDes: '',
              strAlbaranOut: '',
              strCodTipoServOut: '',
              dPesoVolpesOut: '',
              dAltoVolpesOut: '',
              dAnchoVolpesOut: '',
              dLargoVolpesOut: '',
              dtFecEntrOut: '',
              strTipoEnvOut: '',
              dtFecHoraAltaOut: '',
              dKmsManOut: '',
              boTecleDesOut: '',
              strCodAgeOriOut: '',
              strCodAgeDesOut: '',
              strCodProDesOut: '',
              dPorteDebOut: '',
              strCodPaisOut: '',
              boRetornoOut: '',
              strGuidOut: ''
            }.freeze
          end
        end
      end
    end
  end
end
