name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fail-fast: false
        ruby-version: [2.6, 2.7, '3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Install poppler-utils
      run: sudo apt-get install poppler-utils
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
